[package]
name = "ascii_display"
version = "0.1.1"
authors = ["dadope"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal_size = "0.1.17"
clap="2.33.3"
dirs="3.0.2"
rand="0.8.3"
